sudo: required
services:
  - docker

before_install:
  - docker build -t hamdan2018/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hamdan2018/docker-react npm run test -- --watchAll=false

